# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Dell Inc, or its subsidiaries.
---
# version: "3.7" - version is obsolete and can be removed/commented out

services:

  opi-test:
    image: docker.io/library/alpine:3.19
    networks:
      - opi
    command: |
      sh -c 'sleep 30 && exit 0'

networks:
  opi:
